# Generated by Django 5.1.2 on 2025-12-19 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteka', '0004_alter_osoba_options_osoba_wlasciciel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='osoba',
            options={'ordering': ['nazwisko'], 'permissions': [('change_osoba_owner', 'Pozwala przypisać innego usera do obiektu Osoba.'), ('change_assign_to_stanowisko', 'Pozwala przypisać osobę do innego stanowiska.')]},
        ),
    ]
